name: Generate Kikudle
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --request POST \
          --url 'https://kikudle.cf12.org/api/generate' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}' \
          --fail 2>&1
